bind_addr = ":8015"
log_level = "debug"
db_postgresql = "host=10.75.40.153 port=5432 dbname=orders sslmode=disable user=postgres password=CjyysqFyybubkznjh287"
db_mongo = "mongodb://sa:nokia@10.75.40.78:27017/"
